### ISSUE TITLE
better test coverage

### ISSUE THREAD

**Issue by iulusoy** [ssciwr/mailcom#21]
increase test coverage and set up coverage report on CI

**Comment by iulusoy** [comment]
To set up the codecov reports, add this to the workflow file:
```
- name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v4.0.1
  with:
    token: ${{ secrets.CODECOV_TOKEN }}
```
I have added the token to the repository secrets. Also, pytest needs to generate the coverage file during the test run.
